INSERT INTO NUMBER_VALUES(ID, NUMBER) VALUES (1, 1);
INSERT INTO NUMBER_VALUES(ID, NUMBER) VALUES (2, 15);
INSERT INTO NUMBER_VALUES(ID, NUMBER) VALUES (3, 5);
INSERT INTO NUMBER_VALUES(ID, NUMBER) VALUES (4, 7);
INSERT INTO NUMBER_VALUES(ID, NUMBER) VALUES (5, 3);